/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMI = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int TIMES = 9;
  /** RegularExpression Id. */
  int DIV = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int LPARN = 15;
  /** RegularExpression Id. */
  int RPARN = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int DIGITS = 19;
  /** RegularExpression Id. */
  int CHARACTER = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\";\"",
    "\",\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"&\"",
    "\"|\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "<NUMBER>",
    "<DIGITS>",
    "<CHARACTER>",
    "<STRING>",
    "<IDENTIFIER>",
  };

}
